@echo off
set GIT="C:\Users\digit\AppData\Local\GitHubDesktop\app-3.5.5\resources\app\git\cmd\git.exe"
%GIT% add --force public/assets/models/0225_good_sleep_double_2_star_137.glb
%GIT% add --force public/assets/models/03t600ab_totaiblaze_6bnr_stove_with_au.glb
%GIT% add --force public/assets/models/100md_all_in_1_double_1370_bed_set_1.glb
%GIT% add --force public/assets/models/100mdsingle_100mdsingle_all_in_1_single_910_bed_set_10.glb
%GIT% add --force public/assets/models/11159_sofa_two_tone_l_shape_bao.glb
%GIT% add --force public/assets/models/121124_better_lux_single_10_star_be.glb
%GIT% add --force public/assets/models/1240_bugatti_namibia_light_brown_so.glb
%GIT% add --force public/assets/models/1310_better_lux_queen_10_star_152.glb
%GIT% add --force public/assets/models/14972_pedestal_rose_baf.glb
%GIT% add --force public/assets/models/150525_spine_o_pedic_queen_15_star.glb
%GIT% add --force public/assets/models/151370_spine_o_pedic_double_15_star.glb
%GIT% add --force public/assets/models/15532_mw_br3082b_coffe_table_round.glb
%GIT% add --force public/assets/models/1570_sevile_bedroom_suet_2pc.glb
%GIT% add --force public/assets/models/16150_romeo_kitchen_scheme_3pc_baf.glb
%GIT% add --force public/assets/models/17030_blanket_box_may_small_baf.glb
%GIT% add --force public/assets/models/17030_blanket_box_may_small_bax.glb
%GIT% add --force public/assets/models/18163_hazel_bedroom_suite_2pc_oak_ba.glb
%GIT% add --force public/assets/models/18682_pedestal_classic_b_grey_baf.glb
%GIT% add --force public/assets/models/19303_blanket_box_classic_b_greyblack_ba.glb
%GIT% add --force public/assets/models/201124_aldo_2_division_cinema_sofa_ca.glb
%GIT% add --force public/assets/models/20903_headboard_legends_apex_gold_in.glb
%GIT% add --force public/assets/models/20936_headboard_legends_sandiego_sle.glb
%GIT% add --force public/assets/models/21302_legends_tag_headboard_gold_ins.glb
%GIT% add --force public/assets/models/21368_texas_robe_2_door.glb
%GIT% add --force public/assets/models/21413_4ts_shelf_white_oak_baf.glb
%GIT% add --force public/assets/models/21518_pedestal_york_baf.glb
%GIT% add --force public/assets/models/21593_desk_snow_white_bookshelf_ba.glb
%GIT% add --force public/assets/models/215_budget_double_1_star_1370_my.glb
%GIT% add --force public/assets/models/21635_florence_black_headboard_baf.glb
%GIT% add --force public/assets/models/21755_layana_headboard_gold_strips.glb
%GIT% add --force public/assets/models/22488_vegas_2door.glb
%GIT% add --force public/assets/models/22488_vegas_2door_kitchen_base_baf.glb
%GIT% add --force public/assets/models/22489_vegas_2pc_kitchen_schem_baf.glb
%GIT% add --force public/assets/models/2269_gas_stove_euroline_4_burner.glb
%GIT% add --force public/assets/models/22785_3ts_shelf_grey_baf.glb
%GIT% add --force public/assets/models/23025_vegas_3door_kitchen_base_baf.glb
%GIT% add --force public/assets/models/24197_texas_chest_of_drawer_only_baf.glb
%GIT% add --force public/assets/models/24198_texas_chest_of_drawer_mirror.glb
%GIT% add --force public/assets/models/251024_sofa_shadow_corner_l_shape_pak.glb
%GIT% add --force public/assets/models/255_bamboo_double_3_star_1370_re.glb
%GIT% add --force public/assets/models/2587_gas_stove_euroline_4_burner.glb
%GIT% add --force public/assets/models/309_better_lux_double_10_star_13.glb
%GIT% add --force public/assets/models/4857_sofa_single_2div_cup_holder_sq.glb
%GIT% add --force public/assets/models/50113hy_kitchenbase_3door_grey_plaza.glb
%GIT% add --force public/assets/models/52500_magnificent_20_star_double_bed.glb
%GIT% add --force public/assets/models/52600_magnificent_king_20_star_bed.glb
%GIT% add --force public/assets/models/5484_chest_of_drawer_white_4_drawer.glb
%GIT% add --force public/assets/models/5900_juliet_daybed_sofa_can_stan.glb
%GIT% add --force public/assets/models/75500_sofa_galaxy_corner_material_ba.glb
%GIT% add --force public/assets/models/8840_empire_headboard_baf.glb
%GIT% commit -m "assets: add 3D models Batch 1/3 (matched)"
%GIT% push origin main
